# Generated by Django 3.0.6 on 2020-05-19 00:02

from django.db import migrations, models
import django.db.models.deletion
import djorm_pgfulltext.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('nick', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('action', models.BooleanField(default=False)),
                ('command', models.CharField(blank=True, max_length=50, null=True)),
                ('host', models.TextField(blank=True, null=True)),
                ('raw', models.TextField(blank=True, null=True)),
                ('room', models.CharField(blank=True, max_length=100, null=True)),
                ('search_index', djorm_pgfulltext.fields.VectorField(db_index=True, default='', editable=False, null=True, serialize=False)),
                ('bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.ChatBot')),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bots.Channel')),
            ],
            options={
                'ordering': ('-timestamp',),
                'index_together': {('channel', 'timestamp')},
            },
        ),
    ]
