# Generated by Django 3.0.14 on 2021-05-27 03:31

from django.db import migrations, models
import django.db.models.deletion
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0002_publicchannels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivePlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', django_jsonfield_backport.models.JSONField(blank=True, default=dict, help_text='User-specified attributes for this plugin {"username": "joe", "api-key": "foo"}')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bots.Channel')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plugins.Plugin')),
            ],
        ),
    ]
