# Generated by Django 3.0.6 on 2020-05-19 00:02

import botbot.core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivePlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', botbot.core.fields.JSONField(blank=True, default={}, help_text='User-specified attributes for this plugin {"username": "joe", "api-key": "foo"}')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bots.Channel')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plugins.Plugin')),
            ],
        ),
    ]
