# Generated by Django 3.0.14 on 2021-05-27 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicChannels',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Public Channel',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bots.channel',),
        ),
    ]
