# Generated by Django 3.0.6 on 2020-05-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='plugins',
            field=models.ManyToManyField(through='plugins.ActivePlugin', to='plugins.Plugin'),
        ),
        migrations.CreateModel(
            name='PublicChannels',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Public Channel',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bots.channel',),
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('name', 'chatbot'), ('slug', 'chatbot')},
        ),
    ]
