# Generated by Django 3.0.14 on 2021-05-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
        ('bots', '0002_publicchannels'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='plugins',
            field=models.ManyToManyField(through='plugins.ActivePlugin', to='plugins.Plugin'),
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('slug', 'chatbot'), ('name', 'chatbot')},
        ),
    ]
